# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "r1.0" ]
  pull_request:
    branches: [ "r1.0" ]

jobs:
  go20_redis7_mysql8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and start containers
        run: docker-compose -f tests/environments/go1.20_redis7_mysql8/docker-compose.yml up -d --build && docker ps
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true

      - name: Build
        run: go mod tidy && go build -v ./...

      - name: Test
        run: go test -race -v ./...
      - name: Benchmark
        run: |
          go test -race -v -cover ./... -bench . -run ^$ -count 10 -benchmem -coverprofile coverage.out -coverpkg ./...
          go tool cover -func coverage.out -o coverage.out
      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1
        if: ${{ runner.os == 'Linux' && matrix.go == '1.20' }} # Runs this on only one of the ci builds.
        with:
          green: 80
          filename: coverage.out

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Apply Code Coverage Badge
          skip_fetch: true
          skip_checkout: true
          file_pattern: ./README.md

      - name: Push Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/go1.20_redis7_mysql8/docker-compose.yml down
  go21_redis7_mysql8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and start containers
        run: docker-compose -f tests/environments/go1.21_redis7_mysql8/docker-compose.yml up -d --build && docker ps
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true

      - name: Build
        run: go mod tidy && go build -v ./...

      - name: Test
        run: go test -race -v ./...
      - name: Benchmark
        run: go test -race -v ./... -bench . -run ^$ -count 10 -benchmem
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/go1.21_redis7_mysql8/docker-compose.yml down